-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMUXCClk0hAGkhbf/
QGUSQHUmDy4h9ljxGbt8cshuTyGgCgYIKoZIzj0DAQehRANCAARlxd3gafD8P8G2
BgcWSQLSCCaAzPqrlmB0JpCwADRkVSQxw3HxF0MRFxY+sV5Y6J0XGXN1wTJTvbZB
7AvJApJh
-----END PRIVATE KEY-----